name: Run MS Build

on:
    push:
      paths:
        - .github/workflows/edgex.build.yml
        - .github/workflows/gitlab-msbuild.yml
    pull_request:
      paths:
        - .github/workflows/edgex.build.yml
        - .github/workflows/gitlab-msbuild.yml

jobs:
  docker-build:
    uses: ./.github/workflows/gitlab-msbuild.yml
    with:
      repo_name: edgex
      gitlab_path: facefirst-engineering
      trigger_release: ${{ github.ref_name == 'main' }}
    secrets: inherit