name: Build Docker images

on:
  push:
  pull_request:

jobs:
  docker-build:
    uses: ./.github/workflows/gitlab-dockerbuild.yml
    strategy:
      matrix:
        image: ['powershell']
    with:
      repo_name: docker
      gitlab_path: facefirst-engineering/devsecops
      # optional
      image_name: ${{ matrix.image }}
      docker_file: "dockerfile.${{ matrix.image }}"
      trigger_release: ${{ github.ref_name == 'main' }}
    secrets: inherit